const $=s=>document.querySelector(s);let songs=[],scrolling=false,raf=null,last=0;
function esc(s){return String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
$("#form").onsubmit=async e=>{e.preventDefault();let q=$("#q").value.trim();if(!q)return;$("#status").textContent="Searching…";try{let r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(q)}&entity=song&limit=40`),d=await r.json();songs=d.results||[];$("#results").innerHTML=songs.map((x,i)=>`<button class="song" data-i="${i}"><img src="${x.artworkUrl100}"><span><b>${esc(x.trackName)}</b><em>${esc(x.artistName)} · ${esc(x.collectionName||"")}</em></span></button>`).join("");$("#status").textContent=`${songs.length} songs found`;document.querySelectorAll(".song").forEach(b=>b.onclick=()=>openSong(songs[+b.dataset.i]));}catch{$("#status").textContent="Search failed."}};
async function openSong(x){stopScroll();$("#results").classList.add("hidden");$("#form").classList.add("hidden");$("#songView").classList.remove("hidden");$("#title").textContent=x.trackName;$("#artist").textContent=x.artistName;$("#cover").src=(x.artworkUrl100||"").replace("100x100bb","300x300bb");$("#tabMeta").textContent=`Search Songsterr for “${x.trackName}” by ${x.artistName}.`;$("#tabLink").href=`https://www.songsterr.com/?pattern=${encodeURIComponent(x.artistName+" "+x.trackName)}&inst=guitar`;$("#lyricsText").textContent="Loading lyrics…";try{let r=await fetch(`https://api.lyrics.ovh/v1/${encodeURIComponent(x.artistName)}/${encodeURIComponent(x.trackName)}`);if(!r.ok)throw 0;let d=await r.json();$("#lyricsText").textContent=d.lyrics||"Lyrics unavailable."}catch{$("#lyricsText").textContent="Lyrics unavailable for this song from the current lyrics source."}}
function tick(t){if(!scrolling)return;if(!last)last=t;let dt=(t-last)/1000;last=t;let speed=Number($("#speed").value);window.scrollBy(0,dt*(7+speed*5));if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-3){stopScroll();return}raf=requestAnimationFrame(tick)}
function startScroll(){if(scrolling)return;scrolling=true;last=0;$("#autoScroll").textContent="⏸ Pause";$("#autoScroll").classList.add("running");raf=requestAnimationFrame(tick)}
function stopScroll(){scrolling=false;last=0;if(raf)cancelAnimationFrame(raf);raf=null;$("#autoScroll").textContent="▶ Auto Scroll";$("#autoScroll").classList.remove("running")}
$("#autoScroll").onclick=()=>scrolling?stopScroll():startScroll();
$("#top").onclick=()=>{stopScroll();$("#lyricsPane").scrollIntoView({behavior:"smooth",block:"start"})};
$("#back").onclick=()=>{stopScroll();$("#songView").classList.add("hidden");$("#results").classList.remove("hidden");$("#form").classList.remove("hidden")};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{if(b.dataset.tab!=="lyricsPane")stopScroll();document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".pane").forEach(p=>p.classList.add("hidden"));$("#"+b.dataset.tab).classList.remove("hidden")});
$("#donate").onclick=()=>$("#modal").classList.remove("hidden");$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#copy").onclick=async()=>{await navigator.clipboard.writeText("714-818-7485");$("#copy").textContent="Copied ✓"};